spring:
  application:
    name: config-server

  config:
    import: "optional:configserver:"

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888
